[2024-10-01T20:00:13.968-0400] {processor.py:186} INFO - Started process (PID=24280) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:00:13.968-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:00:13.969-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:00:13.968-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:00:13.983-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:00:13.983-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:00:13.983-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:00:13.983-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:00:13.983-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:00:14.009-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-01T20:18:03.869-0400] {processor.py:186} INFO - Started process (PID=39871) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:18:03.871-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:18:03.871-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:18:03.871-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:18:03.888-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:18:03.888-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:18:03.888-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:18:03.888-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:18:03.888-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:18:03.914-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-01T20:19:47.572-0400] {processor.py:186} INFO - Started process (PID=50120) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:19:47.573-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:19:47.574-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:19:47.573-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:19:47.589-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:19:47.589-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:19:47.589-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:19:47.589-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:19:47.589-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:19:47.615-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-01T20:22:15.042-0400] {processor.py:186} INFO - Started process (PID=64798) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:22:15.043-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:22:15.043-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:22:15.043-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:22:15.057-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:22:15.057-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:22:15.057-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:22:15.057-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:22:15.057-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:22:15.084-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-01T20:24:40.289-0400] {processor.py:186} INFO - Started process (PID=79137) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:24:40.289-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:24:40.290-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:24:40.290-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:24:40.304-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:24:40.303-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:24:40.304-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:24:40.304-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:24:40.304-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:24:40.330-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-01T20:27:08.815-0400] {processor.py:186} INFO - Started process (PID=93860) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:27:08.816-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:27:08.816-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:27:08.816-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:27:08.831-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:27:08.831-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:27:08.831-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:27:08.831-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:27:08.831-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:27:08.859-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-10-01T20:29:32.665-0400] {processor.py:186} INFO - Started process (PID=9459) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:29:32.666-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:29:32.667-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:29:32.667-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:29:32.683-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:29:32.682-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:29:32.683-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:29:32.683-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:29:32.683-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:29:32.709-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-10-01T20:48:49.256-0400] {processor.py:186} INFO - Started process (PID=23713) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:48:49.258-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:48:49.258-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:48:49.258-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:48:49.273-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:48:49.273-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:48:49.273-0400] {logging_mixin.py:190} INFO - [2024-10-01T20:48:49.273-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:48:49.273-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:48:49.298-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-01T21:07:20.366-0400] {processor.py:186} INFO - Started process (PID=38157) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T21:07:20.368-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T21:07:20.368-0400] {logging_mixin.py:190} INFO - [2024-10-01T21:07:20.368-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T21:07:20.383-0400] {logging_mixin.py:190} INFO - [2024-10-01T21:07:20.383-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T21:07:20.383-0400] {logging_mixin.py:190} INFO - [2024-10-01T21:07:20.383-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T21:07:20.383-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T21:07:20.408-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-01T21:24:34.284-0400] {processor.py:186} INFO - Started process (PID=53009) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T21:24:34.285-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T21:24:34.286-0400] {logging_mixin.py:190} INFO - [2024-10-01T21:24:34.286-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T21:24:34.301-0400] {logging_mixin.py:190} INFO - [2024-10-01T21:24:34.300-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T21:24:34.301-0400] {logging_mixin.py:190} INFO - [2024-10-01T21:24:34.301-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T21:24:34.301-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T21:24:34.326-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-01T21:44:42.705-0400] {processor.py:186} INFO - Started process (PID=67776) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T21:44:42.706-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T21:44:42.706-0400] {logging_mixin.py:190} INFO - [2024-10-01T21:44:42.706-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T21:44:42.721-0400] {logging_mixin.py:190} INFO - [2024-10-01T21:44:42.721-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T21:44:42.721-0400] {logging_mixin.py:190} INFO - [2024-10-01T21:44:42.721-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T21:44:42.721-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T21:44:42.747-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-01T22:04:25.978-0400] {processor.py:186} INFO - Started process (PID=82184) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:04:25.979-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T22:04:25.979-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:04:25.979-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:04:25.994-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:04:25.994-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T22:04:25.994-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:04:25.994-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T22:04:25.994-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:04:26.019-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-01T22:21:55.269-0400] {processor.py:186} INFO - Started process (PID=96584) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:21:55.270-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T22:21:55.271-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:21:55.271-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:21:55.285-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:21:55.284-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T22:21:55.285-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:21:55.285-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T22:21:55.285-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:21:55.310-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-01T22:26:34.092-0400] {processor.py:186} INFO - Started process (PID=11225) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:26:34.093-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T22:26:34.094-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:26:34.094-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:26:34.107-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:26:34.107-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T22:26:34.108-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:26:34.108-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T22:26:34.108-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:26:34.132-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-01T22:44:50.936-0400] {processor.py:186} INFO - Started process (PID=25266) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:44:50.937-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T22:44:50.937-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:44:50.937-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:44:50.952-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:44:50.951-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T22:44:50.952-0400] {logging_mixin.py:190} INFO - [2024-10-01T22:44:50.952-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T22:44:50.952-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T22:44:50.976-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-01T23:02:43.861-0400] {processor.py:186} INFO - Started process (PID=39720) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T23:02:43.861-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T23:02:43.862-0400] {logging_mixin.py:190} INFO - [2024-10-01T23:02:43.862-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T23:02:43.875-0400] {logging_mixin.py:190} INFO - [2024-10-01T23:02:43.875-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T23:02:43.875-0400] {logging_mixin.py:190} INFO - [2024-10-01T23:02:43.875-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T23:02:43.875-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T23:02:43.901-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-01T23:27:01.083-0400] {processor.py:186} INFO - Started process (PID=55444) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T23:27:01.084-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T23:27:01.084-0400] {logging_mixin.py:190} INFO - [2024-10-01T23:27:01.084-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T23:27:01.098-0400] {logging_mixin.py:190} INFO - [2024-10-01T23:27:01.097-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T23:27:01.098-0400] {logging_mixin.py:190} INFO - [2024-10-01T23:27:01.098-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T23:27:01.098-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T23:27:01.123-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-01T23:45:10.404-0400] {processor.py:186} INFO - Started process (PID=69483) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T23:45:10.404-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T23:45:10.405-0400] {logging_mixin.py:190} INFO - [2024-10-01T23:45:10.405-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T23:45:10.419-0400] {logging_mixin.py:190} INFO - [2024-10-01T23:45:10.418-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T23:45:10.419-0400] {logging_mixin.py:190} INFO - [2024-10-01T23:45:10.419-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T23:45:10.419-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T23:45:10.444-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T00:03:04.841-0400] {processor.py:186} INFO - Started process (PID=85136) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:03:04.842-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T00:03:04.843-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:03:04.842-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:03:04.858-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:03:04.857-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T00:03:04.858-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:03:04.858-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T00:03:04.858-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:03:04.883-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T00:22:10.674-0400] {processor.py:186} INFO - Started process (PID=99889) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:22:10.674-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T00:22:10.675-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:22:10.675-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:22:10.690-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:22:10.690-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T00:22:10.690-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:22:10.690-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T00:22:10.690-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:22:10.717-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-10-02T00:27:11.775-0400] {processor.py:186} INFO - Started process (PID=14780) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:27:11.776-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T00:27:11.776-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:27:11.776-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:27:11.790-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:27:11.789-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T00:27:11.790-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:27:11.790-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T00:27:11.790-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:27:11.814-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T00:45:47.523-0400] {processor.py:186} INFO - Started process (PID=29502) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:45:47.523-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T00:45:47.524-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:45:47.523-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:45:47.539-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:45:47.539-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T00:45:47.539-0400] {logging_mixin.py:190} INFO - [2024-10-02T00:45:47.539-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T00:45:47.539-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T00:45:47.565-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T01:05:28.560-0400] {processor.py:186} INFO - Started process (PID=43402) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:05:28.561-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T01:05:28.561-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:05:28.561-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:05:28.576-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:05:28.576-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T01:05:28.576-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:05:28.576-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T01:05:28.576-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:05:28.601-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T01:07:57.930-0400] {processor.py:186} INFO - Started process (PID=58077) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:07:57.931-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T01:07:57.931-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:07:57.931-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:07:57.947-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:07:57.946-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T01:07:57.947-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:07:57.947-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T01:07:57.947-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:07:57.973-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-10-02T01:28:47.485-0400] {processor.py:186} INFO - Started process (PID=74583) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:28:47.486-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T01:28:47.486-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:28:47.486-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:28:47.500-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:28:47.500-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T01:28:47.500-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:28:47.500-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T01:28:47.500-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:28:47.527-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T01:45:55.660-0400] {processor.py:186} INFO - Started process (PID=84738) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:45:55.661-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T01:45:55.661-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:45:55.661-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:45:55.675-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:45:55.675-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T01:45:55.675-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:45:55.675-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T01:45:55.675-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:45:55.699-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T01:48:21.416-0400] {processor.py:186} INFO - Started process (PID=99283) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:48:21.417-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T01:48:21.417-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:48:21.417-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:48:21.433-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:48:21.432-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T01:48:21.433-0400] {logging_mixin.py:190} INFO - [2024-10-02T01:48:21.433-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T01:48:21.433-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T01:48:21.459-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T02:05:22.440-0400] {processor.py:186} INFO - Started process (PID=7120) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:05:22.441-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T02:05:22.442-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:05:22.441-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:05:22.456-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:05:22.456-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T02:05:22.456-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:05:22.456-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T02:05:22.456-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:05:22.481-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T02:24:15.622-0400] {processor.py:186} INFO - Started process (PID=16721) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:24:15.623-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T02:24:15.624-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:24:15.624-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:24:15.639-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:24:15.638-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T02:24:15.639-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:24:15.639-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T02:24:15.639-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:24:15.663-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T02:29:05.060-0400] {processor.py:186} INFO - Started process (PID=30756) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:29:05.061-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T02:29:05.061-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:29:05.061-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:29:05.075-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:29:05.075-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T02:29:05.075-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:29:05.075-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T02:29:05.075-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:29:05.100-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T02:48:55.656-0400] {processor.py:186} INFO - Started process (PID=44672) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:48:55.657-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T02:48:55.658-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:48:55.658-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:48:55.674-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:48:55.673-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T02:48:55.674-0400] {logging_mixin.py:190} INFO - [2024-10-02T02:48:55.674-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T02:48:55.674-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T02:48:55.702-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-10-02T03:06:58.945-0400] {processor.py:186} INFO - Started process (PID=58717) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:06:58.946-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T03:06:58.946-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:06:58.946-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:06:58.963-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:06:58.962-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T03:06:58.963-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:06:58.963-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T03:06:58.963-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:06:58.991-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-10-02T03:24:31.063-0400] {processor.py:186} INFO - Started process (PID=73338) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:24:31.064-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T03:24:31.064-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:24:31.064-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:24:31.081-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:24:31.080-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T03:24:31.081-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:24:31.081-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T03:24:31.081-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:24:31.107-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-02T03:26:59.730-0400] {processor.py:186} INFO - Started process (PID=87905) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:26:59.730-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T03:26:59.731-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:26:59.731-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:26:59.745-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:26:59.745-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T03:26:59.745-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:26:59.745-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T03:26:59.745-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:26:59.770-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T03:30:52.528-0400] {processor.py:186} INFO - Started process (PID=95399) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:30:52.529-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T03:30:52.529-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:30:52.529-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:30:52.545-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:30:52.544-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T03:30:52.545-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:30:52.545-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T03:30:52.545-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:30:52.569-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T03:43:14.630-0400] {processor.py:186} INFO - Started process (PID=5549) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:43:14.631-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T03:43:14.631-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:43:14.631-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:43:14.645-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:43:14.644-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T03:43:14.645-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:43:14.645-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T03:43:14.645-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:43:14.670-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T03:46:42.751-0400] {processor.py:186} INFO - Started process (PID=12986) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:46:42.753-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T03:46:42.753-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:46:42.753-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:46:42.769-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:46:42.769-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T03:46:42.769-0400] {logging_mixin.py:190} INFO - [2024-10-02T03:46:42.769-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T03:46:42.769-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T03:46:42.796-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-02T04:04:58.072-0400] {processor.py:186} INFO - Started process (PID=23140) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:04:58.074-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T04:04:58.074-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:04:58.074-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:04:58.089-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:04:58.089-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T04:04:58.089-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:04:58.089-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T04:04:58.089-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:04:58.115-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T04:22:30.582-0400] {processor.py:186} INFO - Started process (PID=38313) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:22:30.583-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T04:22:30.584-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:22:30.584-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:22:30.600-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:22:30.599-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T04:22:30.600-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:22:30.600-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T04:22:30.600-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:22:30.628-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-10-02T04:41:28.488-0400] {processor.py:186} INFO - Started process (PID=53268) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:41:28.489-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T04:41:28.489-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:41:28.489-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:41:28.504-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:41:28.503-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T04:41:28.504-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:41:28.504-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T04:41:28.504-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:41:28.529-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T04:59:51.689-0400] {processor.py:186} INFO - Started process (PID=67402) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:59:51.690-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T04:59:51.690-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:59:51.690-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:59:51.706-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:59:51.706-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T04:59:51.706-0400] {logging_mixin.py:190} INFO - [2024-10-02T04:59:51.706-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T04:59:51.706-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T04:59:51.731-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T05:19:21.049-0400] {processor.py:186} INFO - Started process (PID=81489) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T05:19:21.051-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T05:19:21.051-0400] {logging_mixin.py:190} INFO - [2024-10-02T05:19:21.051-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T05:19:21.066-0400] {logging_mixin.py:190} INFO - [2024-10-02T05:19:21.065-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T05:19:21.066-0400] {logging_mixin.py:190} INFO - [2024-10-02T05:19:21.066-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T05:19:21.066-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T05:19:21.091-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T05:36:57.659-0400] {processor.py:186} INFO - Started process (PID=96613) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T05:36:57.660-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T05:36:57.661-0400] {logging_mixin.py:190} INFO - [2024-10-02T05:36:57.661-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T05:36:57.674-0400] {logging_mixin.py:190} INFO - [2024-10-02T05:36:57.674-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T05:36:57.674-0400] {logging_mixin.py:190} INFO - [2024-10-02T05:36:57.674-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T05:36:57.674-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T05:36:57.699-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T05:54:36.140-0400] {processor.py:186} INFO - Started process (PID=11507) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T05:54:36.142-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T05:54:36.142-0400] {logging_mixin.py:190} INFO - [2024-10-02T05:54:36.142-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T05:54:36.157-0400] {logging_mixin.py:190} INFO - [2024-10-02T05:54:36.156-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T05:54:36.157-0400] {logging_mixin.py:190} INFO - [2024-10-02T05:54:36.157-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T05:54:36.157-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T05:54:36.181-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T06:12:22.831-0400] {processor.py:186} INFO - Started process (PID=25839) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T06:12:22.833-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T06:12:22.833-0400] {logging_mixin.py:190} INFO - [2024-10-02T06:12:22.833-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T06:12:22.847-0400] {logging_mixin.py:190} INFO - [2024-10-02T06:12:22.846-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T06:12:22.847-0400] {logging_mixin.py:190} INFO - [2024-10-02T06:12:22.847-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T06:12:22.847-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T06:12:22.872-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T06:30:10.588-0400] {processor.py:186} INFO - Started process (PID=40515) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T06:30:10.589-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T06:30:10.590-0400] {logging_mixin.py:190} INFO - [2024-10-02T06:30:10.590-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T06:30:10.604-0400] {logging_mixin.py:190} INFO - [2024-10-02T06:30:10.604-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T06:30:10.604-0400] {logging_mixin.py:190} INFO - [2024-10-02T06:30:10.604-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T06:30:10.604-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T06:30:10.629-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T06:49:10.570-0400] {processor.py:186} INFO - Started process (PID=54610) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T06:49:10.570-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T06:49:10.571-0400] {logging_mixin.py:190} INFO - [2024-10-02T06:49:10.571-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T06:49:10.585-0400] {logging_mixin.py:190} INFO - [2024-10-02T06:49:10.585-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T06:49:10.585-0400] {logging_mixin.py:190} INFO - [2024-10-02T06:49:10.585-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T06:49:10.585-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T06:49:10.612-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T07:07:58.100-0400] {processor.py:186} INFO - Started process (PID=68546) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T07:07:58.102-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T07:07:58.102-0400] {logging_mixin.py:190} INFO - [2024-10-02T07:07:58.102-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T07:07:58.117-0400] {logging_mixin.py:190} INFO - [2024-10-02T07:07:58.117-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T07:07:58.117-0400] {logging_mixin.py:190} INFO - [2024-10-02T07:07:58.117-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T07:07:58.117-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T07:07:58.145-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-02T07:25:50.831-0400] {processor.py:186} INFO - Started process (PID=83425) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T07:25:50.833-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T07:25:50.833-0400] {logging_mixin.py:190} INFO - [2024-10-02T07:25:50.833-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T07:25:50.847-0400] {logging_mixin.py:190} INFO - [2024-10-02T07:25:50.847-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T07:25:50.847-0400] {logging_mixin.py:190} INFO - [2024-10-02T07:25:50.847-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T07:25:50.847-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T07:25:50.872-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T07:43:52.331-0400] {processor.py:186} INFO - Started process (PID=97866) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T07:43:52.333-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T07:43:52.333-0400] {logging_mixin.py:190} INFO - [2024-10-02T07:43:52.333-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T07:43:52.350-0400] {logging_mixin.py:190} INFO - [2024-10-02T07:43:52.349-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T07:43:52.350-0400] {logging_mixin.py:190} INFO - [2024-10-02T07:43:52.350-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T07:43:52.350-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T07:43:52.377-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-10-02T08:02:24.149-0400] {processor.py:186} INFO - Started process (PID=12374) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:02:24.149-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T08:02:24.150-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:02:24.150-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:02:24.168-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:02:24.167-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T08:02:24.168-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:02:24.168-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T08:02:24.168-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:02:24.197-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2024-10-02T08:21:14.660-0400] {processor.py:186} INFO - Started process (PID=31310) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:21:14.662-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T08:21:14.662-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:21:14.662-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:21:14.676-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:21:14.676-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T08:21:14.676-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:21:14.676-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T08:21:14.676-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:21:14.700-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T08:40:55.571-0400] {processor.py:186} INFO - Started process (PID=46113) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:40:55.572-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T08:40:55.572-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:40:55.572-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:40:55.586-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:40:55.586-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T08:40:55.586-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:40:55.586-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T08:40:55.586-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:40:55.611-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T08:44:35.395-0400] {processor.py:186} INFO - Started process (PID=61583) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:44:35.396-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T08:44:35.396-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:44:35.396-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:44:35.410-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:44:35.410-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T08:44:35.411-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:44:35.410-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T08:44:35.411-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:44:35.436-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T08:57:47.767-0400] {processor.py:186} INFO - Started process (PID=78551) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:57:47.768-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T08:57:47.769-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:57:47.769-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:57:47.783-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:57:47.783-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T08:57:47.784-0400] {logging_mixin.py:190} INFO - [2024-10-02T08:57:47.784-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T08:57:47.784-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T08:57:47.809-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T09:00:13.912-0400] {processor.py:186} INFO - Started process (PID=95603) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:00:13.913-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:00:13.913-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:00:13.913-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:00:13.928-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:00:13.928-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:00:13.928-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:00:13.928-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:00:13.928-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:00:13.953-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T09:02:43.379-0400] {processor.py:186} INFO - Started process (PID=11533) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:02:43.380-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:02:43.381-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:02:43.381-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:02:43.399-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:02:43.399-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:02:43.400-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:02:43.400-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:02:43.400-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:02:43.428-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2024-10-02T09:05:11.224-0400] {processor.py:186} INFO - Started process (PID=27259) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:05:11.225-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:05:11.225-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:05:11.225-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:05:11.242-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:05:11.241-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:05:11.242-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:05:11.242-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:05:11.242-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:05:11.269-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-02T09:07:35.654-0400] {processor.py:186} INFO - Started process (PID=42280) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:07:35.655-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:07:35.655-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:07:35.655-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:07:35.670-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:07:35.670-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:07:35.671-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:07:35.670-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:07:35.671-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:07:35.699-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-02T09:10:03.118-0400] {processor.py:186} INFO - Started process (PID=57701) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:10:03.119-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:10:03.119-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:10:03.119-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:10:03.135-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:10:03.135-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:10:03.135-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:10:03.135-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:10:03.135-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:10:03.161-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-10-02T09:12:30.052-0400] {processor.py:186} INFO - Started process (PID=73151) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:12:30.054-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:12:30.054-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:12:30.054-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:12:30.069-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:12:30.068-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:12:30.069-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:12:30.069-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:12:30.069-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:12:30.095-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T09:14:55.257-0400] {processor.py:186} INFO - Started process (PID=88195) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:14:55.259-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:14:55.259-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:14:55.259-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:14:55.273-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:14:55.273-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:14:55.273-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:14:55.273-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:14:55.273-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:14:55.300-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T09:17:22.225-0400] {processor.py:186} INFO - Started process (PID=3841) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:17:22.226-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:17:22.227-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:17:22.227-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:17:22.240-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:17:22.240-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:17:22.241-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:17:22.241-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:17:22.241-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:17:22.266-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-02T09:19:46.156-0400] {processor.py:186} INFO - Started process (PID=18898) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:19:46.157-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:19:46.157-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:19:46.157-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:19:46.172-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:19:46.171-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:19:46.172-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:19:46.172-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:19:46.172-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:19:46.198-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T09:22:13.091-0400] {processor.py:186} INFO - Started process (PID=34406) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:22:13.092-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:22:13.093-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:22:13.093-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:22:13.107-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:22:13.107-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:22:13.107-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:22:13.107-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:22:13.107-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:22:13.132-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T09:24:38.661-0400] {processor.py:186} INFO - Started process (PID=49644) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:24:38.662-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:24:38.663-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:24:38.662-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:24:38.678-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:24:38.677-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:24:38.678-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:24:38.678-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:24:38.678-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:24:38.703-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T09:27:14.239-0400] {processor.py:186} INFO - Started process (PID=65837) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:27:14.241-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:27:14.241-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:27:14.241-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:27:14.258-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:27:14.257-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:27:14.258-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:27:14.258-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:27:14.258-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:27:14.286-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2024-10-02T09:29:46.068-0400] {processor.py:186} INFO - Started process (PID=82479) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:29:46.070-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:29:46.070-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:29:46.070-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:29:46.086-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:29:46.086-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:29:46.086-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:29:46.086-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:29:46.086-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:29:46.113-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-02T09:32:28.331-0400] {processor.py:186} INFO - Started process (PID=99550) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:32:28.334-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:32:28.335-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:32:28.334-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:32:28.357-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:32:28.356-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:32:28.357-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:32:28.357-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:32:28.357-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:32:28.387-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-10-02T09:35:08.496-0400] {processor.py:186} INFO - Started process (PID=16725) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:35:08.498-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:35:08.498-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:35:08.498-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:35:08.514-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:35:08.514-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:35:08.514-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:35:08.514-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:35:08.514-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:35:08.541-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-02T09:37:46.486-0400] {processor.py:186} INFO - Started process (PID=33218) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:37:46.487-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:37:46.487-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:37:46.487-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:37:46.505-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:37:46.504-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:37:46.505-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:37:46.505-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:37:46.505-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:37:46.532-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2024-10-02T09:40:30.510-0400] {processor.py:186} INFO - Started process (PID=50366) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:40:30.511-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:40:30.511-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:40:30.511-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:40:30.532-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:40:30.531-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:40:30.532-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:40:30.532-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:40:30.532-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:40:30.563-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2024-10-02T09:43:03.493-0400] {processor.py:186} INFO - Started process (PID=66442) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:43:03.495-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:43:03.495-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:43:03.495-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:43:03.509-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:43:03.509-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:43:03.509-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:43:03.509-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:43:03.510-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:43:03.535-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T09:45:33.415-0400] {processor.py:186} INFO - Started process (PID=82139) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:45:33.417-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:45:33.417-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:45:33.417-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:45:33.432-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:45:33.432-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:45:33.432-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:45:33.432-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:45:33.433-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:45:33.459-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-10-02T09:48:07.078-0400] {processor.py:186} INFO - Started process (PID=98551) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:48:07.079-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:48:07.080-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:48:07.079-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:48:07.098-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:48:07.097-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:48:07.098-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:48:07.098-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:48:07.098-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:48:07.126-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2024-10-02T09:50:40.210-0400] {processor.py:186} INFO - Started process (PID=15055) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:50:40.210-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:50:40.211-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:50:40.211-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:50:40.229-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:50:40.229-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:50:40.229-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:50:40.229-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:50:40.229-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:50:40.258-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2024-10-02T09:53:09.977-0400] {processor.py:186} INFO - Started process (PID=30812) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:53:09.979-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:53:09.979-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:53:09.979-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:53:09.994-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:53:09.993-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:53:09.994-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:53:09.994-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:53:09.994-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:53:10.019-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T09:55:37.366-0400] {processor.py:186} INFO - Started process (PID=46248) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:55:37.368-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:55:37.368-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:55:37.368-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:55:37.386-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:55:37.385-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:55:37.386-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:55:37.386-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:55:37.386-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:55:37.414-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2024-10-02T09:58:07.028-0400] {processor.py:186} INFO - Started process (PID=61936) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:58:07.029-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T09:58:07.029-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:58:07.029-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:58:07.046-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:58:07.045-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T09:58:07.046-0400] {logging_mixin.py:190} INFO - [2024-10-02T09:58:07.046-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T09:58:07.046-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T09:58:07.075-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2024-10-02T10:00:33.245-0400] {processor.py:186} INFO - Started process (PID=77023) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:00:33.246-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:00:33.246-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:00:33.246-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:00:33.262-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:00:33.262-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:00:33.262-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:00:33.262-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:00:33.263-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:00:33.290-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-02T10:02:58.361-0400] {processor.py:186} INFO - Started process (PID=92266) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:02:58.362-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:02:58.363-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:02:58.362-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:02:58.379-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:02:58.378-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:02:58.379-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:02:58.379-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:02:58.379-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:02:58.408-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2024-10-02T10:05:28.829-0400] {processor.py:186} INFO - Started process (PID=8332) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:05:28.830-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:05:28.830-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:05:28.830-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:05:28.846-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:05:28.846-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:05:28.846-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:05:28.846-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:05:28.846-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:05:28.873-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-10-02T10:07:57.572-0400] {processor.py:186} INFO - Started process (PID=24173) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:07:57.573-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:07:57.574-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:07:57.574-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:07:57.588-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:07:57.588-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:07:57.588-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:07:57.588-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:07:57.588-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:07:57.613-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T10:10:27.094-0400] {processor.py:186} INFO - Started process (PID=39787) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:10:27.096-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:10:27.096-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:10:27.096-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:10:27.113-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:10:27.113-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:10:27.113-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:10:27.113-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:10:27.113-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:10:27.140-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-10-02T10:12:55.962-0400] {processor.py:186} INFO - Started process (PID=55364) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:12:55.964-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:12:55.964-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:12:55.964-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:12:55.978-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:12:55.978-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:12:55.979-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:12:55.978-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:12:55.979-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:12:56.004-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T10:15:22.601-0400] {processor.py:186} INFO - Started process (PID=70582) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:15:22.602-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:15:22.602-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:15:22.602-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:15:22.619-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:15:22.618-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:15:22.619-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:15:22.619-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:15:22.619-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:15:22.644-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T10:17:49.297-0400] {processor.py:186} INFO - Started process (PID=86016) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:17:49.297-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:17:49.298-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:17:49.298-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:17:49.312-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:17:49.312-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:17:49.312-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:17:49.312-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:17:49.312-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:17:49.338-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T10:20:19.187-0400] {processor.py:186} INFO - Started process (PID=2093) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:20:19.187-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:20:19.188-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:20:19.188-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:20:19.202-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:20:19.202-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:20:19.202-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:20:19.202-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:20:19.202-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:20:19.228-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-10-02T10:22:46.673-0400] {processor.py:186} INFO - Started process (PID=17705) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:22:46.674-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:22:46.675-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:22:46.675-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:22:46.689-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:22:46.689-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:22:46.689-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:22:46.689-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:22:46.689-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:22:46.715-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T10:25:13.338-0400] {processor.py:186} INFO - Started process (PID=33255) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:25:13.339-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:25:13.340-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:25:13.340-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:25:13.355-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:25:13.354-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:25:13.355-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:25:13.355-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:25:13.355-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:25:13.381-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-10-02T10:27:40.466-0400] {processor.py:186} INFO - Started process (PID=48474) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:27:40.467-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:27:40.467-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:27:40.467-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:27:40.482-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:27:40.482-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:27:40.482-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:27:40.482-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:27:40.482-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:27:40.508-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-02T10:30:06.757-0400] {processor.py:186} INFO - Started process (PID=63838) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:30:06.758-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:30:06.759-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:30:06.759-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:30:06.774-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:30:06.774-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:30:06.774-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:30:06.774-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:30:06.774-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:30:06.800-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-02T10:32:38.878-0400] {processor.py:186} INFO - Started process (PID=81570) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:32:38.879-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:32:38.879-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:32:38.879-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:32:38.895-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:32:38.895-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:32:38.895-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:32:38.895-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:32:38.895-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:32:38.924-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2024-10-02T10:35:09.372-0400] {processor.py:186} INFO - Started process (PID=97254) to work on /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:35:09.373-0400] {processor.py:914} INFO - Processing file /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-02T10:35:09.373-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:35:09.373-0400] {dagbag.py:588} INFO - Filling up the DagBag from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:35:09.387-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:35:09.387-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-02T10:35:09.387-0400] {logging_mixin.py:190} INFO - [2024-10-02T10:35:09.387-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-02T10:35:09.387-0400] {processor.py:927} WARNING - No viable dags retrieved from /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-02T10:35:09.413-0400] {processor.py:208} INFO - Processing /Users/forrest.murray/Documents/devel/dbx-airflow/.venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
